const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type, x-admin-key",
  "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS"
};
const json = (data, status=200) => new Response(JSON.stringify(data), {status, headers:{"content-type":"application/json; charset=utf-8", ...cors}});
function ok(request, env) { const key=request.headers.get("x-admin-key"); return !!env.ADMIN_KEY && !!key && key===env.ADMIN_KEY; }
async function init(env){ await env.DB.prepare(`CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',image_url TEXT NOT NULL DEFAULT '',price INTEGER NOT NULL DEFAULT 0,old_price INTEGER NOT NULL DEFAULT 0,stock INTEGER NOT NULL DEFAULT 0,max_qty INTEGER NOT NULL DEFAULT 99,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run(); }

const ADMIN_HTML = `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Green Moon — لوحة المنتجات</title><style>
*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Tahoma,Arial;background:#f5f7f5;color:#123}header{background:#0b3d2e;color:#fff;padding:18px;position:sticky;top:0;z-index:5}h1{margin:0;font-size:22px}.wrap{max-width:900px;margin:auto;padding:14px}.card{background:#fff;border-radius:16px;padding:16px;margin:12px 0;box-shadow:0 3px 16px #00000010}label{display:block;font-weight:700;margin:10px 0 5px}input,textarea,button{font:inherit}input,textarea{width:100%;padding:11px;border:1px solid #d7ddd9;border-radius:10px;background:#fff}textarea{min-height:80px}button{border:0;border-radius:10px;padding:11px 14px;cursor:pointer}.primary{background:#0b3d2e;color:#fff}.muted{background:#edf1ee}.danger{background:#b42318;color:#fff}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.item{display:flex;gap:12px;align-items:center;border-top:1px solid #eee;padding:12px 0}.item img{width:72px;height:72px;object-fit:cover;border-radius:10px;background:#eee}.item b{display:block}.small{font-size:13px;color:#667}.preview{display:none;width:100px;height:100px;object-fit:cover;border-radius:12px;margin-top:8px}.status{padding:10px;border-radius:10px;background:#f0f6f2;margin-bottom:10px;display:none}.hint{font-size:12px;color:#68736d}.login{max-width:420px;margin:60px auto}.hide{display:none!important}@media(max-width:600px){.row{grid-template-columns:1fr}}
</style></head><body><header><div class="wrap"><h1>🌿 Green Moon — لوحة إدارة المنتجات</h1></div></header><main class="wrap">
<section id="login" class="card login"><h2>دخول الإدارة</h2><p class="small">اكتب مفتاح الإدارة الخاص بك.</p><input id="key" type="password" placeholder="ADMIN KEY"><div class="actions"><button class="primary" onclick="login()">دخول</button></div></section>
<section id="app" class="hide"><div id="status" class="status"></div><div class="card"><h2 id="formTitle">إضافة منتج</h2><input id="id" type="hidden"><label>اسم المنتج</label><input id="name" placeholder="مثال: بامبو كيرلي 90 سم"><label>صورة المنتج</label><input id="image" type="file" accept="image/*" onchange="previewImage()"><img id="preview" class="preview"><div class="hint">اختار الصورة مباشرة من الموبايل. سيتم رفعها تلقائيًا.</div><label>السعر</label><input id="price" type="number"><div class="row"><div><label>السعر القديم</label><input id="old_price" type="number"></div><div><label>المخزون</label><input id="stock" type="number"></div></div><label>أقصى كمية للطلب</label><input id="max_qty" type="number" value="99"><label>الوصف</label><textarea id="description" placeholder="وصف مختصر للمنتج"></textarea><div class="actions"><button class="primary" onclick="save()">حفظ المنتج</button><button class="muted" onclick="clearForm()">إضافة جديد</button><button class="muted" onclick="load()">تحديث القائمة</button></div></div>
<div class="card"><h2>المنتجات</h2><div id="list">جاري التحميل...</div></div></section></main>
<script>
let token="", currentImage=""; const $=id=>document.getElementById(id); function msg(t){$('status').textContent=t;$('status').style.display='block';setTimeout(()=>{$('status').style.display='none'},3000)}
function login(){token=$('key').value.trim(); if(!token)return; $('login').classList.add('hide');$('app').classList.remove('hide');load()}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'x-admin-key':token};const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'حدث خطأ');return d}
function previewImage(){const f=$('image').files[0];if(!f)return;const u=URL.createObjectURL(f);$('preview').src=u;$('preview').style.display='block'}
async function uploadImage(){const f=$('image').files[0];if(!f)return currentImage;const fd=new FormData();fd.append('image',f);const d=await api('/api/admin/upload',{method:'POST',body:fd});return d.url}
async function save(){try{const id=$('id').value;let image_url=currentImage;if($('image').files[0]) image_url=await uploadImage();const b={name:$('name').value.trim(),image_url,price:Number($('price').value)||0,old_price:Number($('old_price').value)||0,stock:Number($('stock').value)||0,max_qty:Number($('max_qty').value)||99,description:$('description').value};if(!b.name)throw Error('اسم المنتج مطلوب');if(id)await api('/api/admin/products/'+id,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(b)});else await api('/api/admin/products',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});msg('تم حفظ المنتج بنجاح ✅');clearForm();load()}catch(e){alert(e.message)}}
function edit(p){$('id').value=p.id;$('name').value=p.name||'';$('price').value=p.price||0;$('old_price').value=p.old_price||0;$('stock').value=p.stock||0;$('max_qty').value=p.max_qty||99;$('description').value=p.description||'';currentImage=p.image_url||'';$('image').value='';$('preview').style.display=currentImage?'block':'none';$('preview').src=currentImage||'';$('formTitle').textContent='تعديل المنتج';scrollTo({top:0,behavior:'smooth'})}
function clearForm(){['id','name','price','old_price','stock','description'].forEach(x=>$(x).value='');$('max_qty').value=99;$('image').value='';$('preview').style.display='none';$('preview').src='';currentImage='';$('formTitle').textContent='إضافة منتج'}
async function load(){try{const d=await api('/api/admin/products');$('list').innerHTML=d.products.length?d.products.map(p=>'<div class="item"><img src="'+(p.image_url||'')+'"><div style="flex:1"><b>'+esc(p.name)+'</b><div class="small">'+p.price+' جنيه • مخزون: '+p.stock+' • '+(p.active?'مفعل':'مخفي')+'</div><div class="actions"><button class="muted" onclick='edit('+JSON.stringify(p)+')'>تعديل</button><button class="danger" onclick='removeP('+p.id+')'>إخفاء</button></div></div></div>').join(''):'لا توجد منتجات بعد.'}catch(e){$('list').textContent=e.message}}
async function removeP(id){if(!confirm('إخفاء المنتج؟'))return;try{await api('/api/admin/products/'+id,{method:'DELETE'});msg('تم إخفاء المنتج');load()}catch(e){alert(e.message)}}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
</script></body></html>`;

export default { async fetch(request,env){ try{ if(request.method==='OPTIONS')return new Response(null,{headers:cors}); await init(env); const u=new URL(request.url);
 if(u.pathname==='/admin' || u.pathname==='/admin/') return new Response(ADMIN_HTML,{headers:{'content-type':'text/html; charset=utf-8'}});
 if(u.pathname.startsWith('/images/') && request.method==='GET'){ if(!env.IMAGES)return new Response('Image storage not configured',{status:503}); const key=decodeURIComponent(u.pathname.slice(8)); const obj=await env.IMAGES.get(key); if(!obj)return new Response('Not found',{status:404}); const h=new Headers();obj.writeHttpMetadata(h);h.set('cache-control','public,max-age=31536000,immutable');return new Response(obj.body,{headers:h}); }
 if(u.pathname==='/' && request.method==='GET')return json({success:true,service:'Green Moon Product API',admin:'/admin'});
 if(u.pathname==='/api/products'&&request.method==='GET'){const r=await env.DB.prepare('SELECT id,name,description,image_url,price,old_price,stock,max_qty,active FROM products WHERE active=1 ORDER BY id DESC').all();return json({success:true,products:r.results||[]});}
 if(u.pathname==='/api/admin/upload'&&request.method==='POST'){if(!ok(request,env))return json({success:false,error:'Unauthorized'},401);if(!env.IMAGES)return json({success:false,error:'R2 image storage is not connected yet'},503);const fd=await request.formData();const f=fd.get('image');if(!f||typeof f.arrayBuffer!=='function')return json({success:false,error:'الصورة مطلوبة'},400);if(!String(f.type||'').startsWith('image/'))return json({success:false,error:'الملف يجب أن يكون صورة'},400);if(f.size>8*1024*1024)return json({success:false,error:'الصورة أكبر من 8MB'},400);const ext=(String(f.name||'jpg').split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const key='products/'+crypto.randomUUID()+'.'+ext;await env.IMAGES.put(key,await f.arrayBuffer(),{httpMetadata:{contentType:f.type||'image/jpeg'}});return json({success:true,url:'/images/'+encodeURIComponent(key)});}
 if(u.pathname==='/api/admin/products'&&request.method==='GET'){if(!ok(request,env))return json({success:false,error:'Unauthorized'},401);const r=await env.DB.prepare('SELECT * FROM products ORDER BY id DESC').all();return json({success:true,products:r.results||[]});}
 if(u.pathname==='/api/admin/products'&&request.method==='POST'){if(!ok(request,env))return json({success:false,error:'Unauthorized'},401);const b=await request.json();if(!String(b.name||'').trim())return json({success:false,error:'اسم المنتج مطلوب'},400);const r=await env.DB.prepare('INSERT INTO products(name,description,image_url,price,old_price,stock,max_qty,active) VALUES(?,?,?,?,?,?,?,1)').bind(String(b.name).trim(),String(b.description||''),String(b.image_url||''),Number(b.price)||0,Number(b.old_price)||0,Math.max(0,Number(b.stock)||0),Math.max(1,Number(b.max_qty)||99)).run();return json({success:true,id:r.meta.last_row_id},201);}
 const m=u.pathname.match(/^\/api\/admin\/products\/(\d+)$/);if(m&&(request.method==='PUT'||request.method==='DELETE')){if(!ok(request,env))return json({success:false,error:'Unauthorized'},401);const id=Number(m[1]);if(request.method==='DELETE'){await env.DB.prepare('UPDATE products SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(id).run();return json({success:true});}const b=await request.json();await env.DB.prepare('UPDATE products SET name=?,description=?,image_url=?,price=?,old_price=?,stock=?,max_qty=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(String(b.name||'').trim(),String(b.description||''),String(b.image_url||''),Number(b.price)||0,Number(b.old_price)||0,Math.max(0,Number(b.stock)||0),Math.max(1,Number(b.max_qty)||99),b.active===false?0:1,id).run();return json({success:true});}
 return json({success:false,error:'Not found'},404);
 }catch(e){return json({success:false,error:String(e?.message||e)},500)}}};
