const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type, x-admin-key",
  "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS"
};
const json = (data, status=200) => new Response(JSON.stringify(data), {status, headers:{"content-type":"application/json; charset=utf-8", ...cors}});
function ok(request, env) { const key=String(request.headers.get("x-admin-key")||'').trim(); const secret=String(env.ADMIN_KEY||'').trim(); return !!secret && !!key && key===secret; }
async function init(env){
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',image_url TEXT NOT NULL DEFAULT '',price INTEGER NOT NULL DEFAULT 0,old_price INTEGER NOT NULL DEFAULT 0,wholesale_price INTEGER NOT NULL DEFAULT 0,category TEXT NOT NULL DEFAULT 'الزرع والنباتات',hot_offer INTEGER NOT NULL DEFAULT 0,discount INTEGER NOT NULL DEFAULT 0,featured INTEGER NOT NULL DEFAULT 0,new_product INTEGER NOT NULL DEFAULT 0,sort_order INTEGER NOT NULL DEFAULT 0,stock INTEGER NOT NULL DEFAULT 0,max_qty INTEGER NOT NULL DEFAULT 99,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
 const cols=[['wholesale_price','INTEGER NOT NULL DEFAULT 0'],['category',"TEXT NOT NULL DEFAULT 'الزرع والنباتات'"],['hot_offer','INTEGER NOT NULL DEFAULT 0'],['discount','INTEGER NOT NULL DEFAULT 0'],['featured','INTEGER NOT NULL DEFAULT 0'],['new_product','INTEGER NOT NULL DEFAULT 0'],['sort_order','INTEGER NOT NULL DEFAULT 0']];
 for(const [c,t] of cols){try{await env.DB.prepare(`ALTER TABLE products ADD COLUMN ${c} ${t}`).run()}catch(e){if(!String(e.message||e).toLowerCase().includes('duplicate column'))throw e}}
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS store_settings (id INTEGER PRIMARY KEY CHECK(id=1),store_name TEXT NOT NULL DEFAULT 'Green Moon Plants and Flowers',store_desc TEXT NOT NULL DEFAULT '',profile_url TEXT NOT NULL DEFAULT '',cover_url TEXT NOT NULL DEFAULT '',style TEXT NOT NULL DEFAULT 'luxury-emerald',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
 await env.DB.prepare(`INSERT OR IGNORE INTO store_settings(id) VALUES(1)`).run();
}

const ADMIN_HTML = `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Green Moon — لوحة التحكم</title><style>
*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Tahoma,Arial;background:#f4f6f3;color:#17382d}header{background:#0a392b;color:#fff;padding:16px;position:sticky;top:0;z-index:5}.wrap{max-width:980px;margin:auto;padding:14px}h1{margin:0;font-size:21px}.tabs{display:flex;gap:8px;overflow:auto;margin:12px 0}.tabs button{white-space:nowrap}.card{background:#fff;border-radius:16px;padding:16px;margin:12px 0;box-shadow:0 4px 18px #0000000d}label{display:block;font-weight:800;margin:9px 0 5px}input,textarea,select,button{font:inherit}input,textarea,select{width:100%;padding:11px;border:1px solid #d6ded9;border-radius:10px;background:#fff}textarea{min-height:85px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.checks{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.checks label{background:#f5f8f5;padding:10px;border-radius:10px;margin:0}.checks input{width:auto}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}button{border:0;border-radius:10px;padding:11px 14px;cursor:pointer}.primary{background:#0a392b;color:#fff}.muted{background:#edf1ee}.danger{background:#b42318;color:#fff}.hide{display:none!important}.item{display:flex;gap:12px;align-items:center;border-top:1px solid #eee;padding:12px 0}.item img{width:74px;height:74px;object-fit:cover;border-radius:11px;background:#eee}.small{font-size:13px;color:#66736d}.badge{display:inline-block;background:#e9f4ee;border-radius:20px;padding:3px 8px;font-size:11px;margin:2px}.styleGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.style{border:2px solid #e3e8e4;border-radius:15px;padding:12px;cursor:pointer}.style.active{border-color:#0a392b}.swatches{display:flex;height:55px;border-radius:10px;overflow:hidden;margin-bottom:8px}.swatches i{flex:1}.preview{max-width:150px;max-height:100px;border-radius:10px;margin-top:8px}.status{padding:10px;border-radius:10px;background:#edf7f0;margin-bottom:10px;display:none}.hint{font-size:12px;color:#68736d}.login{max-width:420px;margin:60px auto}@media(max-width:600px){.row,.styleGrid{grid-template-columns:1fr}}
</style></head><body><header><div class="wrap"><h1>🌿 Green Moon — لوحة التحكم</h1></div></header><main class="wrap">
<section id="login" class="card login"><h2>دخول الإدارة</h2><p class="small">مفتاح الإدارة سري ولا تشاركه مع أي شخص.</p><input id="key" type="password" placeholder="ADMIN KEY"><div class="actions"><button class="primary" onclick="login()">دخول</button></div></section>
<section id="app" class="hide"><div id="status" class="status"></div><div class="tabs"><button class="primary" onclick="showTab('products')">🌿 المنتجات</button><button class="muted" onclick="showTab('store')">🎨 مظهر المتجر</button></div>
<div id="productsTab"><div class="card"><h2 id="formTitle">إضافة منتج</h2><input id="id" type="hidden"><label>اسم المنتج</label><input id="name" placeholder="مثال: بامبو كيرلي 90 سم"><label>صورة المنتج</label><input id="image" type="file" accept="image/*" onchange="previewImage()"><img id="preview" class="preview"><div class="hint">رفع الصورة يحتاج R2 مربوطًا باسم IMAGES. ويمكنك مؤقتًا إدخال رابط الصورة من خانة الصورة الحالية عند التعديل.</div><label>رابط الصورة الحالي (اختياري)</label><input id="image_url" placeholder="https://..."><div class="row"><div><label>سعر الجملة 🔐</label><input id="wholesale_price" type="number"></div><div><label>السعر قبل الخصم</label><input id="old_price" type="number"></div></div><label>السعر بعد الخصم / السعر الحالي</label><input id="price" type="number"><div class="row"><div><label>القسم</label><select id="category"><option>الزرع والنباتات</option><option>الأصص والمزهريات</option><option>الأسمدة والمستلزمات</option><option>الأحجار والزينة</option><option>الهدايا والباقات</option><option>أخرى</option></select></div><div><label>المخزون</label><input id="stock" type="number"></div></div><div class="checks"><label><input id="hot_offer" type="checkbox"> 🔥 عرض ساخن</label><label><input id="discount" type="checkbox"> 🏷️ تخفيض</label><label><input id="featured" type="checkbox"> ⭐ مميز</label><label><input id="new_product" type="checkbox"> 🆕 جديد</label></div><label>ترتيب المنتج</label><input id="sort_order" type="number" value="0"><label>أقصى كمية للطلب</label><input id="max_qty" type="number" value="99"><label>الوصف</label><textarea id="description"></textarea><div class="actions"><button class="primary" onclick="save()">حفظ المنتج</button><button class="muted" onclick="clearForm()">إضافة جديد</button><button class="muted" onclick="load()">تحديث</button></div></div><div class="card"><h2>المنتجات</h2><div id="list">جاري التحميل...</div></div></div>
<div id="storeTab" class="hide"><div class="card"><h2>🎨 هوية المتجر</h2><label>اسم المتجر</label><input id="store_name"><label>وصف المتجر</label><textarea id="store_desc"></textarea><label>رابط صورة البروفايل / اللوجو</label><input id="profile_url" placeholder="https://..."><label>رابط صورة الغلاف</label><input id="cover_url" placeholder="https://..."><div class="actions"><button class="primary" onclick="saveSettings()">حفظ الهوية</button></div></div><div class="card"><h2>👑 اختر الاستايل</h2><div class="styleGrid" id="styleGrid"></div><div class="actions"><button class="primary" onclick="saveSettings()">تفعيل الاستايل المختار</button></div></div></div>
</section></main><script>
let token='',currentImage='',settings={},selectedStyle='luxury-emerald';const $=id=>document.getElementById(id);function msg(t){$('status').textContent=t;$('status').style.display='block';setTimeout(()=>$('status').style.display='none',3000)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'x-admin-key':token};const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'حدث خطأ');return d}
async function login(){const k=$('key').value.trim();if(!k){msg('اكتب مفتاح الإدارة أولاً');return}token=k;msg('جاري التحقق من مفتاح الإدارة…');try{const d=await api('/api/admin/products');$('login').classList.add('hide');$('app').classList.remove('hide');$('status').style.display='none';await load();await loadSettings()}catch(e){token='';$('status').textContent=e.message==='Unauthorized'?'مفتاح الإدارة غير صحيح ❌':('تعذر تسجيل الدخول: '+e.message);$('status').style.display='block'}}
function showTab(t){$('productsTab').classList.toggle('hide',t!=='products');$('storeTab').classList.toggle('hide',t!=='store')}
function previewImage(){const f=$('image').files[0];if(!f)return;$('preview').src=URL.createObjectURL(f);$('preview').style.display='block'}
async function uploadImage(){const f=$('image').files[0];if(!f)return currentImage;const fd=new FormData();fd.append('image',f);const d=await api('/api/admin/upload',{method:'POST',body:fd});return d.url}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function productUrl(id){return location.origin.replace('green-moon-products','catalog')+'/product/'+id}
async function save(){try{const id=$('id').value;let image_url=$('image_url').value.trim()||currentImage;if($('image').files[0])image_url=await uploadImage();const b={name:$('name').value.trim(),image_url,price:+$('price').value||0,old_price:+$('old_price').value||0,wholesale_price:+$('wholesale_price').value||0,category:$('category').value,hot_offer:$('hot_offer').checked,discount:$('discount').checked,featured:$('featured').checked,new_product:$('new_product').checked,sort_order:+$('sort_order').value||0,stock:+$('stock').value||0,max_qty:+$('max_qty').value||99,description:$('description').value};if(!b.name)throw Error('اسم المنتج مطلوب');if(id)await api('/api/admin/products/'+id,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(b)});else await api('/api/admin/products',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});msg('تم حفظ المنتج بنجاح ✅');clearForm();load()}catch(e){alert(e.message)}}
function edit(p){$('id').value=p.id;$('name').value=p.name||'';$('price').value=p.price||0;$('old_price').value=p.old_price||0;$('wholesale_price').value=p.wholesale_price||0;$('category').value=p.category||'الزرع والنباتات';$('hot_offer').checked=!!p.hot_offer;$('discount').checked=!!p.discount;$('featured').checked=!!p.featured;$('new_product').checked=!!p.new_product;$('sort_order').value=p.sort_order||0;$('stock').value=p.stock||0;$('max_qty').value=p.max_qty||99;$('description').value=p.description||'';currentImage=p.image_url||'';$('image_url').value=currentImage;$('image').value='';$('preview').style.display=currentImage?'block':'none';$('preview').src=currentImage;$('formTitle').textContent='تعديل المنتج';showTab('products');scrollTo({top:0,behavior:'smooth'})}
function clearForm(){['id','name','price','old_price','wholesale_price','stock','description','image_url'].forEach(x=>$(x).value='');$('sort_order').value=0;$('max_qty').value=99;$('category').value='الزرع والنباتات';['hot_offer','discount','featured','new_product'].forEach(x=>$(x).checked=false);$('image').value='';$('preview').style.display='none';currentImage='';$('formTitle').textContent='إضافة منتج'}
async function load(){try{const d=await api('/api/admin/products');$('list').innerHTML=d.products.length?d.products.map(p=>'<div class="item"><img src="'+(p.image_url||'')+'"><div style="flex:1"><b>'+esc(p.name)+'</b><div class="small">بيع: '+p.price+' ج • جملة: '+p.wholesale_price+' ج • مخزون: '+p.stock+'</div><div>'+(p.hot_offer?'<span class="badge">🔥 عرض ساخن</span>':'')+(p.discount?'<span class="badge">🏷️ تخفيض</span>':'')+(p.featured?'<span class="badge">⭐ مميز</span>':'')+(p.new_product?'<span class="badge">🆕 جديد</span>':'')+'</div><div class="actions"><button class="muted" onclick='edit('+JSON.stringify(p)+')'>تعديل</button><button class="muted" onclick='navigator.clipboard.writeText(productUrl('+p.id+')).then(()=>msg("تم نسخ رابط المنتج ✅"))'>🔗 نسخ الرابط</button><button class="danger" onclick='removeP('+p.id+')'>إخفاء</button></div></div></div>').join(''):'لا توجد منتجات بعد.'}catch(e){$('list').textContent=e.message}}
async function removeP(id){if(!confirm('إخفاء المنتج؟'))return;try{await api('/api/admin/products/'+id,{method:'DELETE'});msg('تم إخفاء المنتج');load()}catch(e){alert(e.message)}}
const styles=[['luxury-emerald','Luxury Emerald',['#073b2a','#c9a227','#f5f0df']],['black-gold','Black & Gold',['#111','#c8a64b','#f7f3e8']],['botanical-cream','Botanical Cream',['#f6f0df','#315c45','#fff']],['forest-premium','Forest Premium',['#123d2d','#d7c59a','#eef0e8']],['royal-green','Royal Green',['#0d513b','#d4af37','#fff']],['minimal-nature','Minimal Nature',['#fff','#315d46','#e9eee8']],['dark-botanical','Dark Botanical',['#071f18','#8abf9b','#172e25']],['modern-glass','Modern Glass',['#102c25','#79a995','#edf6f2']],['luxury-boutique','Luxury Boutique',['#1d3128','#b99a5b','#efe8da']],['editorial-garden','Editorial Garden',['#24352b','#d5b978','#f4f1e7']]];
function renderStyles(){ $('styleGrid').innerHTML=styles.map(s=>'<div class="style '+(selectedStyle===s[0]?'active':'')+'" onclick="selectedStyle=\''+s[0]+'\';renderStyles()"><div class="swatches">'+s[1].map(c=>'<i style="background:'+c+'"></i>').join('')+'</div><b>'+s[1]+'</b></div>').join('') }
async function loadSettings(){const d=await api('/api/admin/settings');settings=d.settings||{};$('store_name').value=settings.store_name||'Green Moon Plants and Flowers';$('store_desc').value=settings.store_desc||'';$('profile_url').value=settings.profile_url||'';$('cover_url').value=settings.cover_url||'';selectedStyle=settings.style||'luxury-emerald';renderStyles()}
async function saveSettings(){try{const b={store_name:$('store_name').value.trim(),store_desc:$('store_desc').value,profile_url:$('profile_url').value.trim(),cover_url:$('cover_url').value.trim(),style:selectedStyle};await api('/api/admin/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(b)});msg('تم حفظ إعدادات المتجر وتفعيل الاستايل ✅')}catch(e){alert(e.message)}}
document.addEventListener('DOMContentLoaded',()=>{const k=$('key');if(k)k.addEventListener('keydown',e=>{if(e.key==='Enter')login()});});</script></body></html>`;


export default { async fetch(request,env){ try{ if(request.method==='OPTIONS')return new Response(null,{headers:cors}); const u=new URL(request.url);
 if(u.pathname==='/admin' || u.pathname==='/admin/') return new Response(ADMIN_HTML,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate'}});
 await init(env);
 if(u.pathname.startsWith('/images/') && request.method==='GET'){ if(!env.IMAGES)return new Response('Image storage not configured',{status:503}); const key=decodeURIComponent(u.pathname.slice(8)); const obj=await env.IMAGES.get(key); if(!obj)return new Response('Not found',{status:404}); const h=new Headers();obj.writeHttpMetadata(h);h.set('cache-control','public,max-age=31536000,immutable');return new Response(obj.body,{headers:h}); }
 if(u.pathname==='/' && request.method==='GET')return json({success:true,service:'Green Moon Product API',admin:'/admin'});
 if(u.pathname==='/api/products'&&request.method==='GET'){const r=await env.DB.prepare('SELECT id,name,description,image_url,price,old_price,wholesale_price,category,hot_offer,discount,featured,new_product,sort_order,stock,max_qty,active FROM products WHERE active=1 ORDER BY sort_order ASC,id DESC').all();return json({success:true,products:r.results||[]});}
 if(u.pathname.match(/^\/api\/products\/(\d+)$/)&&request.method==='GET'){const id=Number(u.pathname.split('/').pop());const r=await env.DB.prepare('SELECT id,name,description,image_url,price,old_price,category,hot_offer,discount,featured,new_product,sort_order,stock,max_qty,active FROM products WHERE id=? AND active=1').bind(id).first();return r?json({success:true,product:r}):json({success:false,error:'Product not found'},404);}
 if(u.pathname==='/api/store'&&request.method==='GET'){const s=await env.DB.prepare('SELECT store_name,store_desc,profile_url,cover_url,style FROM store_settings WHERE id=1').first();return json({success:true,settings:s||{}});}
 if(u.pathname==='/api/admin/settings'&&request.method==='GET'){if(!ok(request,env))return json({success:false,error:'Unauthorized'},401);const s=await env.DB.prepare('SELECT store_name,store_desc,profile_url,cover_url,style FROM store_settings WHERE id=1').first();return json({success:true,settings:s||{}});}
 if(u.pathname==='/api/admin/settings'&&request.method==='PUT'){if(!ok(request,env))return json({success:false,error:'Unauthorized'},401);const b=await request.json();await env.DB.prepare('UPDATE store_settings SET store_name=?,store_desc=?,profile_url=?,cover_url=?,style=?,updated_at=CURRENT_TIMESTAMP WHERE id=1').bind(String(b.store_name||'Green Moon Plants and Flowers'),String(b.store_desc||''),String(b.profile_url||''),String(b.cover_url||''),String(b.style||'luxury-emerald')).run();return json({success:true});}
 if(u.pathname==='/api/admin/upload'&&request.method==='POST'){if(!ok(request,env))return json({success:false,error:'Unauthorized'},401);if(!env.IMAGES)return json({success:false,error:'R2 image storage is not connected yet'},503);const fd=await request.formData();const f=fd.get('image');if(!f||typeof f.arrayBuffer!=='function')return json({success:false,error:'الصورة مطلوبة'},400);if(!String(f.type||'').startsWith('image/'))return json({success:false,error:'الملف يجب أن يكون صورة'},400);if(f.size>8*1024*1024)return json({success:false,error:'الصورة أكبر من 8MB'},400);const ext=(String(f.name||'jpg').split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const key='products/'+crypto.randomUUID()+'.'+ext;await env.IMAGES.put(key,await f.arrayBuffer(),{httpMetadata:{contentType:f.type||'image/jpeg'}});return json({success:true,url:'/images/'+encodeURIComponent(key)});}
 if(u.pathname==='/api/admin/products'&&request.method==='GET'){if(!ok(request,env))return json({success:false,error:'Unauthorized'},401);const r=await env.DB.prepare('SELECT * FROM products ORDER BY id DESC').all();return json({success:true,products:r.results||[]});}
 if(u.pathname==='/api/admin/products'&&request.method==='POST'){if(!ok(request,env))return json({success:false,error:'Unauthorized'},401);const b=await request.json();if(!String(b.name||'').trim())return json({success:false,error:'اسم المنتج مطلوب'},400);const r=await env.DB.prepare('INSERT INTO products(name,description,image_url,price,old_price,wholesale_price,category,hot_offer,discount,featured,new_product,sort_order,stock,max_qty,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)').bind(String(b.name).trim(),String(b.description||''),String(b.image_url||''),Number(b.price)||0,Number(b.old_price)||0,Math.max(0,Number(b.wholesale_price)||0),String(b.category||'الزرع والنباتات'),b.hot_offer?1:0,b.discount?1:0,b.featured?1:0,b.new_product?1:0,Number(b.sort_order)||0,Math.max(0,Number(b.stock)||0),Math.max(1,Number(b.max_qty)||99)).run();return json({success:true,id:r.meta.last_row_id},201);}
 const m=u.pathname.match(/^\/api\/admin\/products\/(\d+)$/);if(m&&(request.method==='PUT'||request.method==='DELETE')){if(!ok(request,env))return json({success:false,error:'Unauthorized'},401);const id=Number(m[1]);if(request.method==='DELETE'){await env.DB.prepare('UPDATE products SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(id).run();return json({success:true});}const b=await request.json();await env.DB.prepare('UPDATE products SET name=?,description=?,image_url=?,price=?,old_price=?,wholesale_price=?,category=?,hot_offer=?,discount=?,featured=?,new_product=?,sort_order=?,stock=?,max_qty=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(String(b.name||'').trim(),String(b.description||''),String(b.image_url||''),Number(b.price)||0,Number(b.old_price)||0,Math.max(0,Number(b.wholesale_price)||0),String(b.category||'الزرع والنباتات'),b.hot_offer?1:0,b.discount?1:0,b.featured?1:0,b.new_product?1:0,Number(b.sort_order)||0,Math.max(0,Number(b.stock)||0),Math.max(1,Number(b.max_qty)||99),b.active===false?0:1,id).run();return json({success:true});}
 return json({success:false,error:'Not found'},404);
 }catch(e){return json({success:false,error:String(e?.message||e)},500)}}};
